//! MODEL 2 — Malicious preprocessing view model.
//!
//! The simulation target is the HONEST-GENERATED part of the corrupted
//! authorities' view:
//!   - honest-generated messages observed by corrupted authorities,
//!   - honest-generated commitments observed by corrupted authorities,
//!   - public transcript entries produced by honest authorities,
//!   - shares/messages delivered from honest authorities to corrupted ones.
//!
//! The adversary's OWN corrupted-party inputs and messages are part of the
//! auxiliary state `AdversaryAuxiliaryState`; they are given to the simulator
//! as context and are NOT simulated output.
//!
//! The simulator never receives any R_EA,i. In the trusted-dealer Shamir
//! special case this is possible because any fewer-than-threshold share
//! vector is distributed independently of the secret (uniform), so the
//! simulator can sample it directly.

use std::collections::HashMap;

use ark_ff::UniformRand;
use rand::SeedableRng;
use rand_chacha::ChaCha20Rng;

use crate::types::{F, PublicParams, ThresholdParams, VoterId};

pub type AuthorityId = u32;

/// The adversary's own contribution to the corrupted authorities' view:
/// inputs it chose and messages it sent. Opaque to the simulator — passed
/// through as context, never generated by it.
#[derive(Debug, Clone, Default)]
pub struct AdversaryAuxiliaryState {
    /// Per corrupted authority: the adversary's chosen inputs/randomness.
    pub corrupted_inputs: HashMap<AuthorityId, Vec<u8>>,
    /// Messages the adversary itself sent during preprocessing.
    pub corrupted_messages: Vec<Vec<u8>>,
}

/// A simulated share-value delivered from the honest dealer/authorities to a
/// corrupted authority for one voter.
#[derive(Debug, Clone, Copy)]
pub struct SimulatedShare {
    pub voter_id: VoterId,
    pub share_index: u64,
    pub value: F,
}

/// The honest-generated portion of the corrupted authorities' joint view.
#[derive(Debug, Clone, Default)]
pub struct SimulatedCorruptedAuthorityView {
    /// Shares delivered from honest parties to each corrupted authority.
    pub honest_messages_to_corrupted: HashMap<AuthorityId, Vec<SimulatedShare>>,
    /// Public transcript entries produced by honest authorities (e.g. the
    /// public registration commitments h_i, which are binding but hiding).
    pub honest_public_transcript: Vec<F>,
}

/// Interface for simulating the honest-generated view of corrupted
/// authorities WITHOUT access to any R_EA,i.
pub trait ThresholdViewSimulator {
    fn simulate_honest_generated_view(
        &self,
        pp: &PublicParams,
        corrupted_authorities: &[AuthorityId],
        aux: &AdversaryAuxiliaryState,
    ) -> SimulatedCorruptedAuthorityView;
}

/// Simulator for the trusted-dealer Shamir special case.
///
/// With |corrupted| < t, the corrupted authorities' shares of each R_EA,i are
/// uniformly and independently distributed, so the simulator samples them
/// uniformly. It holds only PUBLIC information (threshold parameters, the
/// voter-id list) plus its own randomness seed — no secrets.
pub struct TrustedDealerShamirSimulator {
    pub params: ThresholdParams,
    /// Public list of registered voter ids.
    pub voter_ids: Vec<VoterId>,
    /// Public registration commitments h_i (already public transcript).
    pub public_commitments: Vec<F>,
    pub seed: u64,
}

impl ThresholdViewSimulator for TrustedDealerShamirSimulator {
    fn simulate_honest_generated_view(
        &self,
        _pp: &PublicParams,
        corrupted_authorities: &[AuthorityId],
        _aux: &AdversaryAuxiliaryState,
    ) -> SimulatedCorruptedAuthorityView {
        assert!(
            corrupted_authorities.len() < self.params.t,
            "simulation is only defined for fewer than t corrupted authorities"
        );
        let mut rng = ChaCha20Rng::seed_from_u64(self.seed);
        let mut honest_messages_to_corrupted = HashMap::new();
        for aid in corrupted_authorities {
            let mut shares = Vec::with_capacity(self.voter_ids.len());
            for vid in &self.voter_ids {
                // < t shares of a Shamir sharing are uniform and independent
                // of the secret: sample them directly.
                shares.push(SimulatedShare {
                    voter_id: *vid,
                    share_index: *aid as u64 + 1,
                    value: F::rand(&mut rng),
                });
            }
            honest_messages_to_corrupted.insert(*aid, shares);
        }
        SimulatedCorruptedAuthorityView {
            honest_messages_to_corrupted,
            honest_public_transcript: self.public_commitments.clone(),
        }
    }
}
